//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by LGit.rc
//
#define IDD_COMMITHISTORY               101
#define IDD_DIFF                        102
#define IDD_FILEPROPS_STATUS            103
#define IDD_ADDFROM                     104
#define IDI_LGIT                        105
#define IDI_DIFF_FILE_A                 106
#define IDI_DIFF_BINARY                 107
#define IDI_DIFF_HUNK                   108
#define IDI_DIFF_ADD                    109
#define IDI_DIFF_DEL                    110
#define IDI_DIFF_FILE_B                 111
#define IDD_CLONE                       112
#define IDD_AUTH_USERPASS               113
#define IDD_CERT_PROMPT                 114
#define IDD_NEW_SIGNATURE               115
#define IDR_HISTORY_MENU                116
#define IDR_DIFF_MENU                   117
#define IDD_COMMITINFO                  118
#define IDD_OPTIONS_COMMIT              119
#define IDD_PUSH_UPSTAIRS               120
#define IDI_HISTORY                     121
#define IDI_DIFF                        122
#define IDD_MERGE_CONFLICTS             123
#define IDD_PULL                        124
#define IDD_OPTIONS_GET                 125
#define IDD_REMOTES                     126
#define IDD_REMOTE_EDIT                 127
#define IDD_EXPLORER                    128
#define IDR_EXPLORER_MENU               129
#define IDD_ABOUT                       130
#define IDD_GITCONFIG                   131
#define IDD_CONFIG_EDIT                 132
#define IDD_FILEPROPS_FILE              133
#define IDD_BRANCHES                    134
#define IDD_BRANCH_ADD                  135
#define IDD_TAGINFO                     136
#define IDR_REFERENCE_MENU              137
#define IDD_TAG_ADD                     138
#define IDD_COMMITINFO_REFERENCES       139
#define IDI_BRANCH                      140
#define IDI_TAG                         141
#define IDI_BRANCH_REMOTE               142
#define IDI_TAG_LIGHT                   143
#define IDD_COMMIT_CREATE               144
#define IDD_REVPARSE                    145
#define IDI_HEAD                        146
#define IDD_CHECKOUT_NOTIFY             147
#define IDC_COMMITHISTORY               1000
#define IDC_STATUS_INDEX_NEW            1003
#define IDC_FILESYSPROPS                1004
#define IDC_ADDSCC_LIST                 1005
#define IDC_STATUS_INDEX_MODIFIED       1006
#define IDC_DIFFTEXT                    1006
#define IDC_STATUS_INDEX_DELETED        1007
#define IDC_STATUS_INDEX_RENAMED        1008
#define IDC_CLONE_URL                   1008
#define IDC_STATUS_INDEX_TYPECHANGE     1009
#define IDC_CLONE_PATH                  1009
#define IDC_CLONE_BROWSE                1010
#define IDC_CLONE_BRANCH                1011
#define IDC_AUTH_USERNAME               1013
#define IDC_AUTH_PASSWORD               1014
#define IDC_STATUS_WT_NEW               1015
#define IDC_AUTH_USERPASS_DESC          1015
#define IDC_STATUS_WT_MODIFIED          1016
#define IDC_VIEW_CERT                   1016
#define IDC_STATUS_WT_DELETED           1017
#define IDC_CERT_MESSAGE                1017
#define IDC_STATUS_WT_RENAMED           1018
#define IDC_CERT_PROMPT_ICON            1018
#define IDC_STATUS_WT_TYPECHANGE        1019
#define IDC_SIG_NAME                    1019
#define IDC_STATUS_WT_UNREADABLE        1020
#define IDC_SIG_MAIL                    1020
#define IDC_STATUS_IGNORED              1021
#define IDC_COMMITINFO_AUTHOR           1021
#define IDC_STATUS_CONFLICTED           1022
#define IDC_COMMITINFO_COMMITTER        1022
#define IDC_OPTIONS_COMMIT_PUSH         1022
#define IDC_COMMITINFO_OID              1023
#define IDC_COMMITINFO_MESSAGE          1024
#define IDC_PUSH_REMOTE                 1026
#define IDC_PUSH_REF                    1027
#define IDC_MERGE_CONFLICT_LIST         1029
#define IDC_PULL_REMOTE                 1030
#define IDC_OPTIONS_COMMIT_PULL         1031
#define IDC_CLONE_EXISTING              1032
#define IDC_REMOTE_LIST                 1033
#define IDC_REMOTE_ADD                  1034
#define IDC_REMOTE_DELETE               1035
#define IDC_REMOTE_SETURL               1036
#define IDC_PULL_MANAGE_REMOTES         1037
#define IDC_PUSH_MANAGE_REMOTES         1038
#define IDC_REMOTE_EDIT_URL             1039
#define IDC_REMOTE_EDIT_NAME            1040
#define IDC_REMOTE_EDIT_PUSHURL         1041
#define IDC_ABOUT_VERSION               1043
#define IDC_CONFIG_LIST                 1044
#define IDC_CONFIG_SET                  1045
#define IDC_CONFIG_DELETE               1046
#define IDC_CONFIG_ADD                  1047
#define IDC_CONFIG_EDIT_NAME            1048
#define IDC_CONFIG_EDIT_VALUE           1049
#define IDC_SIGNATURE_MAKE_DEFAULT      1050
#define IDC_PULL_FETCH                  1051
#define IDC_FILEPROPS_STAGE_TYPE        1058
#define IDC_BRANCH_LIST                 1059
#define IDC_BRANCH_ADD_NAME             1062
#define IDC_BRANCH_ADD_FORCE            1063
#define IDC_BRANCH_ADD_BASED_ON         1064
#define IDC_BRANCH_ADD_CHECKOUT         1065
#define IDC_TAGINFO_MESSAGE             1065
#define IDC_TAGINFO_OID                 1066
#define IDC_TAGINFO_AUTHOR              1067
#define IDC_TAG_ADD_MESSAGE             1068
#define IDC_TAG_ADD_NAME                1069
#define IDC_TAG_ADD_BASED_ON            1070
#define IDC_TAG_ADD_FORCE               1071
#define IDC_COMMITINFO_REFERENCES       1072
#define IDC_EXPLORER_FILES              1073
#define IDC_ABOUT_WEB                   1074
#define IDC_COMMIT_CREATE_MESSAGE       1075
#define IDC_REVPARSE_SPEC               1076
#define IDC_COMMIT_CREATE_AUTHOR        1077
#define IDC_COMMIT_CREATE_CHANGEAUTHOR  1078
#define IDC_COMMIT_CREATE_COMMITTER     1079
#define IDC_CHECKOUT_NOTIFY_LIST        1079
#define IDC_COMMIT_CREATE_CHANGECOMMITTER 1080
#define ID_HISTORY_CLOSE                40001
#define ID_DIFF_COPY                    40002
#define ID_DIFF_CLOSE                   40003
#define ID_DIFF_SAVE                    40004
#define ID_HISTORY_COMMIT_DIFF          40005
#define ID_HISTORY_COMMIT_INFO          40006
#define ID_EXPLORER_HELP_ABOUT          40009
#define ID_EXPLORER_REMOTE_MANAGEREMOTES 40010
#define ID_EXPLORER_REMOTE_PUSH         40011
#define ID_EXPLORER_REMOTE_PULL         40012
#define ID_EXPLORER_REPOSITORY_CLOSE    40013
#define ID_EXPLORER_REPOSITORY_HISTORY  40016
#define ID_EXPLORER_REPOSITORY_REFRESH  40017
#define ID_EXPLORER_CONFIG_REPOSITORY   40018
#define ID_EXPLORER_CONFIG_GLOBAL       40019
#define ID_EXPLORER_REPOSITORY_BRANCHES 40020
#define ID_HISTORY_COMMIT_CHECKOUT      40021
#define ID_HISTORY_COMMIT_REVERT        40022
#define ID_HISTORY_COMMIT_RESET_HARD    40024
#define ID_REFERENCE_VIEW               40025
#define ID_REFERENCE_CHECKOUT           40026
#define ID_REFERENCE_MERGE              40027
#define ID_REFERENCE_REMOVE             40028
#define ID_REFERENCE_HISTORY            40029
#define ID_REFERENCE_DIFF               40030
#define ID_REFERENCE_CLOSE              40031
#define ID_BRANCH_ADD                   40032
#define ID_TAG_ADD                      40033
#define ID_EXPLORER_REPOSITORY_APPLYPATCH 40035
#define ID_EXPLORER_REPOSITORY_DIFFFROMSTAGE 40036
#define ID_EXPLORER_STAGE_UPDATE        40037
#define ID_EXPLORER_STAGE_ADDFILES      40038
#define ID_EXPLORER_STAGE_REMOVE        40039
#define ID_EXPLORER_STAGE_UNSTAGE       40040
#define ID_EXPLORER_STAGE_COMMITSTAGED  40041
#define ID_EXPLORER_STAGE_REVERTTOSTAGED 40042
#define ID_EXPLORER_STAGE_REVERTTOHEAD  40043
#define ID_EXPLORER_STAGE_FILEPROPERTIES 40044
#define ID_EXPLORER_FILE_HISTORY        40045
#define ID_EXPLORER_FILE_DIFFFROMSTAGE  40046
#define ID_EXPLORER_STAGE_UPDATEALL     40047
#define ID_EXPLORER_STAGE_ADDALL        40048
#define ID_EXPLORER_REPOSITORY_OPEN     40049
#define ID_EXPLORER_FILE_OPEN           40051
#define ID_EXPLORER_VIEW_SHOWUNCHANGED  40052
#define ID_EXPLORER_VIEW_SHOWUNTRACKED  40053
#define ID_EXPLORER_VIEW_SHOWIGNORED    40054
#define ID_EXPLORER_REPOSITORY_OPENINWINDOWS 40055
#define ID_EXPLORER_STAGE_AMENDLASTCOMMIT 40056
#define ID_EXPLORER_REPOSITORY_CHECKOUT 40057
#define ID_EXPLORER_DIFF_DIFFFROMREVISION 40058
#define ID_EXPLORER_FILE_DIFFFROMREVISION 40059
#define ID_HISTORY_REFRESH              40060
#define ID_REFERENCE_REFRESH            40061
#define ID_EXPLORER_REPOSITORY_CREATESHORTCUTONDESKTOP 40062

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         40063
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
